CREATE TABLE WL_USER (
  OBJECT_ID     BIGINT PRIMARY KEY AUTO_INCREMENT,
  VERSION       BIGINT              NOT NULL DEFAULT 1,
  USER_ID       VARCHAR(255) UNIQUE NOT NULL,
  FIRST_NAME    VARCHAR(255)        NOT NULL,
  LAST_NAME     VARCHAR(255)        NOT NULL,
  EMAIL_ADDRESS VARCHAR(255)        NULL
);

CREATE TABLE WL_BLOG_ENTRY (
  OBJECT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  VERSION   BIGINT              NOT NULL DEFAULT 1,
  ENTRY_ID  VARCHAR(255) UNIQUE NOT NULL,
  TITLE     VARCHAR(255)        NOT NULL,
  CONTENT   VARCHAR(1000)       NOT NULL,
  AUTHOR_ID BIGINT              NOT NULL,
  CREATED   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT FK_ENTRY_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES WL_USER (OBJECT_ID)
);
